#!/usr/bin/python

"""
Application to request a cert from a certmaster.
Takes no arguments, uses /etc/certmaster/minion.conf

Copyright 2008, Red Hat, Inc
Michael DeHaan <mdehaan@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import distutils.sysconfig

from certmaster import requester

if __name__ == "__main__":
    requester.request_cert()
